name: Check Localization File Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find and check all localization .txt files
        run: |
          # Find and check each .txt file in the correct localization folder
          find ./game/citadel/resource/localization -name "*.txt" | while read file; do
            echo "Checking format of $file"

            # Ensure it contains the "lang" block at any point
            if ! grep -qP '\s*\"lang\"\s*\{' "$file"; then
              echo "$file: Missing 'lang' block."
              exit 1
            fi

            # Ensure it contains the "Tokens" block at any point
            if ! grep -qP '\s*\"Tokens\"\s*\{' "$file"; then
              echo "$file: Missing 'Tokens' block."
              exit 1
            fi

            # Check for matching braces in "lang" and "Tokens" sections
            lang_opening_count=$(grep -oP '\s*\"lang\"\s*\{' "$file" | wc -l)
            lang_closing_count=$(grep -oP '^\s*\}' "$file" | wc -l)
            if [ $lang_opening_count -ne $lang_closing_count ]; then
              echo "$file: Mismatched opening/closing braces in 'lang' block."
              exit 1
            fi

            tokens_opening_count=$(grep -oP '\s*\"Tokens\"\s*\{' "$file" | wc -l)
            tokens_closing_count=$(grep -oP '^\s*\}' "$file" | wc -l)
            if [ $tokens_opening_count -ne $tokens_closing_count ]; then
              echo "$file: Mismatched opening/closing braces in 'Tokens' block."
              exit 1
            fi

            # Ensure file contains only valid straight quotes for key-value pairs
            if grep -P '[“”]' "$file"; then
              echo "Invalid quotation marks found in $file. Use straight quotes (\") only."
              exit 1
            fi

            # Ensure all lines inside Tokens follow the "key" "value" structure or are comments
            if ! grep -P "^\s*(//.*|\"[a-zA-Z0-9_]+\"\s*\"[^\"]+\")\s*$" "$file"; then
              echo "$file is incorrectly formatted. Make sure every line follows \"key\" \"value\" pattern or is a comment starting with //."
              exit 1
            fi
          done

      - name: Format check passed
        run: echo "All localization files are correctly formatted!"
